#!/bin/sh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

## Enable services
systemctl enable systemd-timesyncd arch-tweaks-hwsetup &> /dev/null

## Copy configs
cp -r /usr/share/arch-tweaks/custom-configs/etc/* /etc/

## Exit gracefully
exit 0
