#!/bin/sh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -f /usr/bin/mkinitcpio ]; then
	# Disable fallback image generation for existing presets
	for FILE in $(ls -A /etc/mkinitcpio.d); do
		sed -i "s/^.*PRESETS=('default' 'fallback').*$/PRESETS=('default')/" /etc/mkinitcpio.d/$FILE
		sed -i "s/^fallback/#&/" /etc/mkinitcpio.d/$FILE
	done

	# Create missing presets
	for KERNEL in $($SCRIPT_DIR/get-installed-kernels); do
		KERNEL_NAME="$(echo $KERNEL | cut -d ';' -f 1)"
		if [ ! -f /etc/mkinitcpio.d/$KERNEL_NAME.preset ]; then
			echo "# mkinitcpio preset file for the '$KERNEL_NAME' package" > /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "#ALL_config=\"/etc/mkinitcpio.conf\"" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "ALL_kver=\"/boot/vmlinuz-$KERNEL_NAME\"" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "PRESETS=('default')" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "#default_config=\"/etc/mkinitcpio.conf\"" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "default_image=\"/boot/initramfs-$KERNEL_NAME.img\"" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "#default_uki=\"/efi/EFI/Linux/arch-$KERNEL_NAME.efi\"" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
			echo "#default_options=\"--splash /usr/share/systemd/bootctl/splash-arch.bmp\"" >> /etc/mkinitcpio.d/$KERNEL_NAME.preset
		fi
	done
else
	rm -rf /etc/mkinitcpio.d /etc/mkinitcpio.conf /etc/mkinitcpio.conf.pacsave
	# Link or copy booster images to initramfs-linux*.img for compatibility with GRUB
	if [ -f /usr/bin/booster ] && [ ! -f /usr/bin/dracut ] && [ -f /boot/booster-linux*.img ]; then
		BOOT_FS="$(df -T /boot | grep -m 1 "/dev/" | xargs | cut -d ' ' -f 2)"
		for BOOSTER_FILE in $(ls /boot/booster-linux*.img); do
			BOOSTER_FILE="$(basename "$BOOSTER_FILE")"
			BOOSTER_INITRAMFS="$(echo "$BOOSTER_FILE" | sed 's/booster-linux/initramfs-linux/g')"
			if [ "$BOOT_FS" == "vfat" ] || [ $BOOT_FS == "exfat" ]; then
				cp /boot/$BOOSTER_FILE /boot/$BOOSTER_INITRAMFS
			else
				ln -sfr /boot/$BOOSTER_FILE /boot/$BOOSTER_INITRAMFS
			fi
		done
	fi
fi
